### ISSUE TITLE
Register Collision Event

### ISSUE THREAD

**Issue by maxwildersmith** [maxwildersmith/SAE#6]
Detect when the main car body collides with something.

**Comment by deckheart** [comment]
1. Used new scene that has textured walls
2. Registered the car and all other collidable entities (i.e. walls, cylinders) as a single collision pair
3. Added a graph that progresses with time and will show whether or not the car is colliding with anything
4. Car will turn bright red when it is colliding; other objects will not change color
5. Changed the velocity in **_test.py_** to **10** to produce a collision

**No collision reading was added to the script
